#ifndef DRAUNE_DSTRUCT_ERROR
#define DRAUNE_DSTRUCT_ERROR

enum
{
    DSTRUCT_NO_ERROR = 0,
    DSTRUCT_MALLOC_ERROR = 1,
    DSTRUCT_VECTOR_ARRAY_NULL = 2,
    DSTRUCT_NOT_IN_VECTOR = 3,
    DSTRUCT_VECTOR_SPACE_OCCUPIED = 4,
    DSTRUCT_STATE_NOT_FOUND = 5,
    DSTRUCT_LINK_STATE_NOT_FOUND = 6,
    DSTRUCT_STATE_MACHINE_NOT_STARTED = 7,
    DSTRUCT_PARAMETER_NULL = 8
};

#endif